### ISSUE TITLE
Can Lazy be constructed as a static?

### ISSUE THREAD

**Issue by rukai** [danieldg/async-once-cell#10]
I'm trying to use Lazy as a global static value to hold a type initialized via an async constructor.
However I cant get it to work, is something like this possible?
It would be nice to have an example in `examples/` if this is possible or documentation as to why its impossible at https://docs.rs/async-once-cell/latest/async_once_cell/struct.Lazy.html maybe directing users towards OnceCell for which I have been able to successfully use as a static.

**Comment by danieldg** [comment]
If you want to actually use `async` syntax, this is currently only possible with unstable rust:
```rust
#![feature(const_async_blocks)]
#![feature(type_alias_impl_trait)]
use async_once_cell::Lazy;
use std::future::Future;

type H = impl Future<Output=i32>;
static LAZY: Lazy<i32, H> = Lazy::new(async { 4 });
```

However, if you create a struct that has an `impl Future`, you can use it today.

**Comment by danieldg** [comment]
You can also use `async` syntax today with a bit of boilerplate:
```rust
use async_once_cell::Lazy;
use std::{future::Future, pin::Pin, task};

struct F(Option<Pin<Box<dyn Future<Output=i32> + Sync + Send>>>);
impl Future for F {
    type Output = i32;
    fn poll(mut self: Pin<&mut Self>, cx: &mut task::Context) -> task::Poll<i32> {
        Pin::new(self.0.get_or_insert_with(|| Box::pin(async {
            4
        }))).poll(cx)
    }
}

static LAZY: Lazy<i32, F> = Lazy::new(F(None));
```

**Comment by WorldSEnder** [comment]
With something like https://github.com/nwtgck/stacklover-rust you can also do this on stable and avoid the Box (~~for now at the expense of not being able to construct it in a const context - this should be fixable though~~ PR for this is up).

```rust
stacklover::define_struct! {
    Foo,
    fn () -> impl Future<Output = i32> + use<> {
        async { 4 }
    },
    impls = (Send, Sync),
}
impl Future for Foo {
    type Output = i32;
    fn poll(self: Pin<&mut Self>, ctx: &mut Context) -> Poll<Self::Output> {
        self.as_pin_mut().poll(ctx)
    }
}
thread_local! {
    static LAZY: Lazy<i32, Foo> = Lazy::new(Foo::new());
}
```
