### ISSUE TITLE
Panic after calling `take`.

### ISSUE THREAD

**Issue by kriomant** [danieldg/async-once-cell#4]
While trying to implement cell with expiration, I found that following code

```rust
/*
[dependencies]
async-once-cell = "*"
tokio = { version = "*", features = ["macros", "rt-multi-thread"] }
*/

#[tokio::main]
async fn main() {
    let mut cell = async_once_cell::OnceCell::new_with(Some(0u64));
    let value = cell.get();
    let _ = cell.take();
    let _ = cell.get_or_init(async { 1 }).await;
    println!("done");
}
```
[playground](https://www.rustexplorer.com/b#%2F*%0A%5Bdependencies%5D%0Aasync-once-cell%20%3D%20%22*%22%0Atokio%20%3D%20%7B%20version%20%3D%20%22*%22%2C%20features%20%3D%20%5B%22macros%22%2C%20%22rt-multi-thread%22%5D%20%7D%0A*%2F%0A%0A%23%5Btokio%3A%3Amain%5D%0Aasync%20fn%20main()%20%7B%0A%20%20%20%20let%20mut%20cell%20%3D%20async_once_cell%3A%3AOnceCell%3A%3Anew_with(Some(0u64))%3B%0A%20%20%20%20let%20_%20%3D%20cell.get()%3B%0A%20%20%20%20let%20_%20%3D%20cell.take()%3B%0A%20%20%20%20let%20_%20%3D%20cell.get_or_init(async%20%7B%201%20%7D).await%3B%0A%20%20%20%20println!(%22done%22)%3B%0A%7D)

causes

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/explorer/.cargo/registry/src/github.com-1ecc6299db9ec823/async-once-cell-0.4.2/src/lib.rs:455:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
here:

```rust
        // Safety: initialized on all paths
        Ok(unsafe { (&*self.value.get()).as_ref().unwrap() })
```

It seems not all paths ensures value is initialised.

**Comment by danieldg** [comment]
Please check if master fixes this; I just noticed that there's a commit to fix this issue but it wasn't included in 0.4.2.  I'll release 0.4.3 with that later today.
